### ISSUE TITLE
Write page 

### ISSUE THREAD

**Issue by taxtist** [PedityOfficial/New-Additions#3]
Please ADD 

Switch to Fancy Pants Editor + Markdown: Syntax and Attach files by dragging & dropping, selecting them, or pasting from the cllipboard. 
(reddit and github style) 

and for YOUTUBE IFRAME tag 
-> check this video 
https://www.youtube.com/watch?v=_LugTZssMdg

![2018-11-13 6 22 24](https://user-images.githubusercontent.com/18159654/48403563-80060900-e771-11e8-9192-d5c0cf99ab03.png)
![2018-11-13 6 22 30](https://user-images.githubusercontent.com/18159654/48403564-80060900-e771-11e8-9ad9-abfd3b136d15.png)
![2018-11-13 6 24 17](https://user-images.githubusercontent.com/18159654/48403565-809e9f80-e771-11e8-9ccd-8b426e31cb67.png)

**Comment by taxtist** [comment]
https://www.youtube.com/watch?v=_LugTZssMdg

**Comment by Pedity-Luffy** [comment]
A better editor is now added in 0.1.3
